apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: joseph-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: joseph
  
  source:
    repoURL: https://github.com/duchai157012/Joseph.git
    targetRevision: main
    path: k8s/argocd/applications
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
