apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: joseph-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: joseph
  
  source:
    repoURL: https://github.com/duchai157012/Joseph.git
    targetRevision: main
    path: k8s/base
  
  destination:
    server: https://kubernetes.default.svc
    namespace: joseph-dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
